# version: '3.8'
services:
  my_beancount:
    container_name: beancount_server
    build:
      context: .
      secrets:
        - github_token
        - git_crypt_key
    secrets:
      - github_token
      - git_crypt_key
    environment:
      - TZ=Asia/Shanghai
    # 不对外暴露端口

  sso_gateway:
    image: nginx:latest
    container_name: sso_gateway
    ports:
      - "8111:8111"  # 对外暴露端口
    volumes:
      - ./sso_nginx.conf:/etc/nginx/conf.d/default.conf
      # 如果要开启https，需要将证书挂载到容器中
      # - ./cert/ssl.pem:/etc/nginx/ssl/ssl.pem
      # - ./cert/ssl.key:/etc/nginx/ssl/ssl.key
    depends_on:
      - sso_auth
      - my_beancount

  sso_auth:
    container_name: sso_auth
    build:
      context: ./sso_auth
      dockerfile: Dockerfile
    volumes:
      - ./sso_auth:/app
    working_dir: /app
    command: python app.py
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - my_beancount

secrets:
  github_token:
    file: ./secrets/github_token.txt
  git_crypt_key:
    file: ./secrets/git_crypt_key